[project]
name = "zatca_erpgulf"
authors = [
    { name = "ERPGulf", email = "support@ERPGulf.com"}
]
description = "Implementaiton of Saudi E-Invoicing Phase-2 on Frappe ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # Frappe and ERPNext are installed and managed by bench.
    "asn1~=2.7.0",
    "cryptography>=41,<47",
    "lxml>=4.9,<7",
    "num2words>=0.5.12,<1",
    "pikepdf>=8,<11",
    "pyqrcode>=1.2.1,<2",
    "requests>=2.28,<3",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
