const assert = require("assert");
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const source = fs.readFileSync(path.resolve(__dirname, "../../public/js/our_sales_invoice.js"), "utf8");
const start = source.indexOf("function zatca_first_present");
const end = source.indexOf("const ZATCA_INVOICE_EXEMPTION_CODES");
const context = {};
vm.createContext(context);
vm.runInContext(`${source.slice(start, end)}\nthis.check = zatca_simplified_b2b_state; this.looks = zatca_customer_name_looks_b2b;`, context);
const invoice = (amount, vat = 15, b2c = 1) => ({ __zatca_company_invoice_enabled: 1, doc: { custom_b2c: b2c, net_total: amount, base_net_total: amount, total_taxes_and_charges: vat, base_total_taxes_and_charges: vat, custom_zatca_status: "" } });
const check = (name, frm, customer, expected) => { customer.country = customer.country || "Saudi Arabia"; assert.strictEqual(Boolean(context.check(frm, customer)), expected, name); };
check("999.99 is below threshold", invoice(999.99), { customer_name: "Acme LLC", tax_id: "", custom_b2c: 1 }, false);
check("1000 with valid VAT warns", invoice(1000), { customer_name: "Customer", tax_id: "311111111111113", custom_b2c: 1 }, true);
check("invalid VAT falls back to company name", invoice(1000), { customer_name: "Acme LLC", tax_id: "123", custom_b2c: 1 }, true);
check("real B2C without B2B indicators does not warn", invoice(1000), { customer_name: "Ali", tax_id: "", custom_b2c: 1 }, false);
check("non-Saudi customer does not warn", invoice(1000), { customer_name: "Acme LLC", tax_id: "311111111111113", custom_b2c: 1, country: "AE" }, false);
check("Standard invoice does not warn", invoice(1000, 15, 0), { customer_name: "Acme LLC", tax_id: "311111111111113", custom_b2c: 0 }, false);
assert.strictEqual(context.looks("Acme Co."), true);
assert.strictEqual(context.looks("Companywide"), false);
console.log("simplified invoice warning tests: 8 passed");
